#pragma once
#define CAMERA_OPENGL_SUPPORT
#define CAMERA_D3D11_SUPPORT

#define CAMERA_DEBUG
#ifdef CAMERA_DEBUG
#define CAMERA_D3D11_ENABLE_DEBUG_LAYER
#define CAMERA_LAUNCH_SYNC
#define CAMERA_RESOURCE_CHECK
#endif
