#pragma once
#define CAMERA_OPENGL_SUPPORT
#ifdef _WIN32
#define CAMERA_D3D11_SUPPORT
#endif

#ifdef CAMERA_DEBUG
#ifdef CAMERA_OPENGL_SUPPORT
#define CAMERA_OPENGL_ENABLE_DEBUG_OUTPUT
#endif
#ifdef CAMERA_D3D11_SUPPORT
#define CAMERA_D3D11_ENABLE_DEBUG_LAYER
#endif
#define CAMERA_SYNC
#define CAMERA_HUNGRY_REPORT
#define CAMERA_RESOURCE_CHECK
#define CAMERA_SINGLE_STREAM
#define CAMERA_MEMORY_MESSAGE
#define CAMERA_SOFTWARE_RENDERER_COUNT_DRAWCALL
#endif

#define TRANSFER_ALIGN 16
#define CACHE_ALIGN 16
